Final clean up
inverted-ai/torchdriveenv pull request #5
Opened 2024-04-22 08:49 UTC by zhangk1551

This PR addressed the comments from @adscib :
```

1. Move scenario definition yaml files into torchdriveenv, so that they're distributed with the package. Without that, the environment is not usable out of the box. The default configuration should load the default training scenarios correctly to reduce the initial effort required of the user.
2. Move everything related to specific RL algorithms, and everything referencing stable_baselines3, out of torchdriveenv and into rl_training.py. We're providing an environment, all the RL code is just an example.
3. Decide whether we're passing tensors or numpy arrays through the gym interface. The current code is incoherent, at least as far as type annotations go. My preference is for tensors, so that we can allow passing gradients through the environment in the future, but if the gym interface requires arrays specifically, there's not much we can do.
4. Remove hard-coded references to "cuda" and check that the environment runs without a GPU.
5. Update docstrings so that they match what's in the code now.

```
For the item 3, I changed them to numpy arrays because it's required by gym.

2024-04-22 19:47 UTC, adscib requested changes
Yes, we should remove the submodule now, as it's no longer needed.

2024-04-22 19:47 UTC, adscib commented on Dockerfile
>  RUN pip install invertedai==0.0.15
```suggestion
RUN pip install invertedai
```

2024-04-22 19:47 UTC, adscib commented on torchdrivesim
Can you remove it altogether now?

2024-04-22 19:47 UTC, adscib commented on torchdriveenv/helpers.py
> +    if device == "cuda":
This is an odd choice, requiring the user to remember how to seed things correctly. I imagine you added this because this code fails if cuda is not available. If that's the case, why not just check if it's available instead of introducing a device argument?

2024-04-22 19:47 UTC, adscib commented on pyproject.toml
> +    "torchdrivesim"
```suggestion
    "torchdrivesim",
```
Makes for nicer diffs in the future

2024-04-22 19:47 UTC, adscib commented on torchdriveenv/gym_env.py
>  class BaselineAlgorithm(Enum):
Remove this class entirely. You can define it in `rl_training`.

2024-04-22 19:47 UTC, adscib commented on torchdriveenv/gym_env.py
> +        self.device = torch.device('cuda' if torch.cuda.is_available() and cfg.device == 'cuda' else 'cpu')
This is rather counterintuitive. If I set the device to `cuda` in config, I would expect to get an error if cuda is not available. Maybe make the device optional in config and default it to cuda if available and cpu otherwise?

2024-04-22 19:47 UTC, adscib commented on torchdriveenv/gym_env.py
> +def build_simulator(cfg: EnvConfig, map_cfg, device, ego_state, scenario=None, car_sequences=None, waypointseq=None):
The `device` argument is unnecessary. `torchdrivesim.Simulator` has a `to` method that you can call after it is constructed, much like for tensors.

2024-04-22 19:47 UTC, adscib commented on torchdriveenv/env_configs/rl_training.yml
Can we remove this from the package? It seems to define the algorithm more so than the environment. The environment part matches the dataclass defaults anyway.

2024-04-23 22:11 UTC, zhangk1551 commented on Dockerfile
>  RUN pip install invertedai==0.0.15
`invertedai` is updated very frequently, and it might not be that safe to use the latest release by default.

We will need some tests in the workflow

2024-04-23 22:11 UTC, zhangk1551 commented on pyproject.toml
> +    "torchdrivesim"
Done.

2024-04-23 22:11 UTC, zhangk1551 commented on torchdriveenv/env_configs/rl_training.yml
Good point. Done.

2024-04-23 22:11 UTC, zhangk1551 commented on torchdriveenv/gym_env.py
>  class BaselineAlgorithm(Enum):
Done.

2024-04-23 22:11 UTC, zhangk1551 commented on torchdriveenv/helpers.py
> +    if device == "cuda":
Done.

2024-04-23 22:11 UTC, zhangk1551 commented on torchdrivesim
Done.

2024-04-23 22:11 UTC, zhangk1551 commented on torchdriveenv/gym_env.py
> +        self.device = torch.device('cuda' if torch.cuda.is_available() and cfg.device == 'cuda' else 'cpu')
Fix.

2024-04-23 22:19 UTC, zhangk1551 commented
Addressed the comments but still need to remove the submodule and do the final test...

2024-04-23 22:46 UTC, adscib approved these changes
Looks good! Please make sure that everything is working, but otherwise I think we're ready for a release.

2024-04-24 02:01 UTC, merged